version: '2' 

services:
  
  eureka:
    build: ./eureka-server/.
    image: eureka-server
    restart: always
    ports:
      - 9091:9091


  gateway:
    build: ./gateway-server/.
    image: gateway-server
    restart: always
    ports:
     - 8765:8765


  microservice:
    build: ./microservice/.
    image: microservice
    restart: always
    ports:
      - 9094:9094


