server:
  port: 9094

eureka:
#  instance:
#    hostname: eureka
#    port: 9091
#    appname: microservice
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

ribbon:
  eureka:
    enabled: true

